#!/bin/bash

PHPMINVERSION='5.6.0'
PHPVERSION=`php -r "echo phpversion();"`
PHPCORRECTVERSION=`php -r "echo version_compare(phpversion(), '$PHPMINVERSION');"`

GREEN="\033[1;32m"
RED="\033[1;31m"
BLUE="\033[1;34m"
YELLOW="\033[1;33m"
ENDCOLOR="\033[0m"

echo -e "${BLUE}[BEGIN]${ENDCOLOR} Beginning Classroom app development build process."
echo

echo -e "${BLUE}[CHECK]${ENDCOLOR} ./config/build.settings exists."
if [ ! -f ./config/build.settings ]
then
    echo -e "${RED}[FAILURE]${ENDCOLOR} The ./config/build.settings file does not exist. Create it from ./config/build.settings.template."
    exit 1
fi
echo -e "${GREEN}[OK]${ENDCOLOR} ./config/build.settings exists."
echo

echo -e "${BLUE}[INSTALL]${ENDCOLOR} Installing Composer."
curl -sS https://getcomposer.org/installer | php >/dev/null 2>&1
chmod +x composer.phar

php composer.phar global require "fxp/composer-asset-plugin:1.0.0"

echo -e "${BLUE}[INSTALL]${ENDCOLOR} Installing Phing."
wget -qO phing.phar http://www.phing.info/get/phing-2.6.1.phar
chmod +x phing.phar
echo

php phing.phar -Dbuild_settings_file=config/build.settings build

exit 0